---
title: "Compartmental Models"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: rmarkdown::html_vignette 
vignette: >
  %\VignetteIndexEntry{Compartmental Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r, echo=FALSE, warning=FALSE, messages=FALSE, purl=F}
suppressMessages(library(knitr))
library(ramp.xde) 
library(ramp.work) 
library(ramp.library) 
library(deSolve) 
```

# 

In this vignette, we describe five basic compartmental models for mosquito-borne pathogens. The models are named by their states: susceptible (S) - exposed (I) - recovered and immune (R), chemoprotected (P), vaccinated (V). Not all models include all of the states. In ramp.xds, there are six compartmental models: SIS, SIPS, SIR, SIRS, SEIR, and SEIRV.

### Variables

+ $I$ is the density of infected humans

+ $H$ is the density of humans

### Parameters

+ $r$ is the rate infections clear

+ $b$ is the fraction of bites by infective mosquitoes that transmit parasites and cause an infection. 

+ $c$ is the fraction of bites on an infectious human that would infect a mosquito. 

### Dynamics

The model defined herein is defined in two parts. To model exposure and infection (*i.e.* the conversion of eir into foi), we assume that the fraction of infective bites that cause an infection is $b$. The dynamics are given by: 

$$
\frac{dI}{dt} = h (H-I)-rI
$$

### Terms 

**Net Infectiousness**

True prevalence is:

$$x = \frac{X}{H}.$$ 

In our implementation, net infectiousness (NI) is linearly proportional to prevalence:

$$c x.$$

**Human Transmitting Capacity**

After exposure, a human would remain infected for $1/r$ days, transmitting with probability $c$ so:

$$c/r$$

**Exposure and Infection**

In this model family, there is no immunity. The model assumes that a constant fraction of all infectious bites, $b$, cause an infection. 



## References

1. Ross R. Report on the Prevention of Malaria in Mauritius. London: Waterlow; 1908.
2. Ross R. The Prevention of Malaria. 2nd ed. London: John Murray; 1911.
3. Smith DL, Battle KE, Hay SI, Barker CM, Scott TW, McKenzie FE. Ross, Macdonald, and a theory for the dynamics and control of mosquito-transmitted pathogens. PLoS Pathog. 2012;8: e1002588. doi:10.1371/journal.ppat.1002588

