---
title: "Adult Mosquito Ecology, Behavior and Infection Dynamics"
subtitle: "An Overview"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Adult Mosquito Ecology, Behavior and Infection Dynamics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r}
library(knitr)
library(ramp.xds)
library(deSolve)
library(ramp.library)
#devtools::load_all()
```

**`ramp.library`** and **`ramp.xds`** aim to provide a comprehensive code library for models of adult mosquito ecology, behaviors, and infection dynamics. The following is a short overview of existing model families:

Modules in **`ramp.xds`**

- `basicM` 

- [`macdonald`](MYZ-Macdonald.html)

- `SI` 

- `GeRM` 

Modules in **`ramp.library`**

- `SEI` 

- `RMG` 

## Macdonald's Model 

+ The [`si`] model The mathematical model Ross published in his 1911 Nature paper was very simple. 

+ The mosquito model  

## Mosquito Age 

## Behavioral State Models 

+ A basic behavioral state model was developed by [Le Menach, *et al.* (2005).](https://doi.org/10.1186/1475-2875-4-23). Here, we have implemented a version of that model as the [RMG model](MYZ-xde-RMG.html)

+ The model [MBITES](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007446) has a system of differential equations with 5 behavioral states. 

+ In [VCOM](https://doi.org/10.1371/journal.pone.0187680), the diagram

## Other 

+ Vertical Transmission 

+ Super-infection 

